---
name: .NET Core Format

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Formating on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        #dotnet: ["3.1", "5.0", "6.0"]
        dotnet: ["6.0"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
          include-prerelease: true

      - name: Setup code formatter
        run: |
          dotnet tool install --tool-path . dotnet-format

      - name: Format projects (--dry-run)
        run: |
          ./dotnet-format --check -v d .
