---
name: ASP.NET Core Format

on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
        os: [ubuntu-18.04, ubuntu-16.04]
        dotnet: ['3.1']

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ matrix.dotnet }}

      - name: Setup code formatter
        run: dotnet tool install --tool-path . dotnet-format

      - name: Format projects (--dry-run)
        run: |
          ./dotnet-format --check --dry-run -v d -w .